name: flutter_floating
description: Flutter privilege-free floating window , support for global , single-page hover , support for edge adsorption , position preservation , up and down the slidable area control and screen rotation after the windowing of the position of the repair and so on.
version: 1.0.8
homepage: https://github.com/Elvisthomme/flutter_floating

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.10
flutter:

  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.lvkang.floating
    iosBundleIdentifier: com.lvkang.floating
